#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 运行 ESLint 和 Prettier
pnpm lint-staged

# 生成 apps 列表
echo "🔄 正在生成最新的 apps 列表..."
node .husky/scripts/generate-apps-list.js

# 将生成的文件添加到暂存区
git add .template.config.json